# Generated by Django 5.0.14 on 2025-08-17 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(help_text="Upload the company's main logo.", upload_to='company_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., AWS Full Stack Interview', max_length=200)),
                ('logo_image', models.ImageField(help_text='The logo for the interview card (e.g., Amazon logo).', upload_to='interview_logos/')),
                ('tag', models.CharField(help_text='e.g., Mix Between Behavioral And Technical', max_length=100)),
                ('short_description', models.TextField(help_text='A short enticing description for the card.')),
                ('job_description_for_ai', models.TextField(help_text='The full, detailed job description to be sent to the AI Interviewer API.')),
                ('slug', models.SlugField(blank=True, help_text='A unique URL-friendly version of the name. Will be auto-generated.', unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='interviews.company')),
            ],
        ),
    ]
